name: docuverse
description: An AI-powered intelligent document assistant

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  file_picker: ^10.2.1
  pdfx: ^2.9.2
  flutter_tts: ^4.2.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.1.11
  google_sign_in: ^6.1.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/sample_docs/
    - .env