// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkankQ6UHOoY7ZZs9WIwYSEjzRpJ4JhUg',
    appId: '1:526413422961:web:a9de5909534653d3cf56d0',
    messagingSenderId: '526413422961',
    projectId: 'docuverse-ai-app',
    authDomain: 'docuverse-ai-app.firebaseapp.com',
    storageBucket: 'docuverse-ai-app.firebasestorage.app',
    measurementId: 'G-QLE7R4CZR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRVYpCgJaXeAd6GsuHA50im7amrSxYaI',
    appId: '1:526413422961:android:a996a4c9870c2bf2cf56d0',
    messagingSenderId: '526413422961',
    projectId: 'docuverse-ai-app',
    storageBucket: 'docuverse-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwnHm3_rOmLo1SEt1_Eijr0U2EmvK9E0g',
    appId: '1:526413422961:ios:fbdfe37255148228cf56d0',
    messagingSenderId: '526413422961',
    projectId: 'docuverse-ai-app',
    storageBucket: 'docuverse-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwnHm3_rOmLo1SEt1_Eijr0U2EmvK9E0g',
    appId: '1:526413422961:ios:fbdfe37255148228cf56d0',
    messagingSenderId: '526413422961',
    projectId: 'docuverse-ai-app',
    storageBucket: 'docuverse-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkankQ6UHOoY7ZZs9WIwYSEjzRpJ4JhUg',
    appId: '1:526413422961:web:68622d90a3b68645cf56d0',
    messagingSenderId: '526413422961',
    projectId: 'docuverse-ai-app',
    authDomain: 'docuverse-ai-app.firebaseapp.com',
    storageBucket: 'docuverse-ai-app.firebasestorage.app',
    measurementId: 'G-7VS2E9NCVE',
  );
}